language: node_js
node_js:
  - '10'
branches:
  only:
    - master
cache:
  yarn: true

script:
  - cd website && yarn install

after_success:
  # deploy to github pages when not in master
  if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]];
  then
    git config --global user.name "${GH_NAME}";
    git config --global user.email "${GH_EMAIL}";
    echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc;
    yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages;
  fi